artifact_uri: file:///E:\mlops\stores\model/0/664b9148c5194be8ab5f7e0d8b7ba486/artifacts
end_time: 1679926272086
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 664b9148c5194be8ab5f7e0d8b7ba486
run_uuid: 664b9148c5194be8ab5f7e0d8b7ba486
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926272049
status: 3
tags: []
user_id: jaykh
