artifact_uri: file:///E:\mlops\stores\model/0/f36941ca72804b0fad6bab1a9194f0dc/artifacts
end_time: 1679926196457
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f36941ca72804b0fad6bab1a9194f0dc
run_uuid: f36941ca72804b0fad6bab1a9194f0dc
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926196423
status: 3
tags: []
user_id: jaykh
