artifact_uri: file:///E:\mlops\stores\model/0/ecb0d2c2e58d4547b3e3048f0b4c9eb4/artifacts
end_time: 1679926192142
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ecb0d2c2e58d4547b3e3048f0b4c9eb4
run_uuid: ecb0d2c2e58d4547b3e3048f0b4c9eb4
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926192109
status: 3
tags: []
user_id: jaykh
