artifact_uri: file:///E:\mlops\stores\model/1/1e1d337a14ab4b77ac23263c143b12c5/artifacts
end_time: 1679950643162
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 1e1d337a14ab4b77ac23263c143b12c5
run_uuid: 1e1d337a14ab4b77ac23263c143b12c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1679950640895
status: 3
tags: []
user_id: jaykh
