artifact_uri: file:///E:\mlops\stores\model/0/4364fa1179e24e5fb46c2fc44e12a2c6/artifacts
end_time: 1679926269569
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 4364fa1179e24e5fb46c2fc44e12a2c6
run_uuid: 4364fa1179e24e5fb46c2fc44e12a2c6
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926269523
status: 3
tags: []
user_id: jaykh
