artifact_uri: file:///E:\mlops\stores\model/0/3538afeffa674066ac256dc22edddf92/artifacts
end_time: 1679926256758
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3538afeffa674066ac256dc22edddf92
run_uuid: 3538afeffa674066ac256dc22edddf92
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926256722
status: 3
tags: []
user_id: jaykh
