artifact_uri: file:///E:\mlops\stores\model/0/873fc62d6a014d3a96082fdd0dbab4f1/artifacts
end_time: 1679926202578
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 873fc62d6a014d3a96082fdd0dbab4f1
run_uuid: 873fc62d6a014d3a96082fdd0dbab4f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926202544
status: 3
tags: []
user_id: jaykh
