artifact_uri: file:///E:\mlops\stores\model/0/de34ce5f93de4c7296b55a64bae3f480/artifacts
end_time: 1679926197189
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: de34ce5f93de4c7296b55a64bae3f480
run_uuid: de34ce5f93de4c7296b55a64bae3f480
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926197157
status: 3
tags: []
user_id: jaykh
