artifact_uri: file:///E:\mlops\stores\model/0/73392fcecf8e47e58cfc356ea9cb5516/artifacts
end_time: 1679926207188
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 73392fcecf8e47e58cfc356ea9cb5516
run_uuid: 73392fcecf8e47e58cfc356ea9cb5516
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926207149
status: 3
tags: []
user_id: jaykh
