artifact_uri: file:///E:\mlops\stores\model/0/46f7d9d4e90c44f4a7315f62d6e9723e/artifacts
end_time: 1679926209376
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 46f7d9d4e90c44f4a7315f62d6e9723e
run_uuid: 46f7d9d4e90c44f4a7315f62d6e9723e
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926209344
status: 3
tags: []
user_id: jaykh
