artifact_uri: file:///E:\mlops\stores\model/0/4a660c8e941d4926a7a2ae09409edf5b/artifacts
end_time: 1679926258422
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 4a660c8e941d4926a7a2ae09409edf5b
run_uuid: 4a660c8e941d4926a7a2ae09409edf5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1679926258387
status: 3
tags: []
user_id: jaykh
